### ISSUE TITLE
Unbundle ABP

### ISSUE THREAD

**Issue by slambert** [slambert/Add-Art#47]
Right now we include AdBlock Plus in the .xpi  

According to the editors at Addons.Mozilla, it's better to keep them separate.

If we take it out, we should check if ABP is installed, and if not, prompt people to install it.

The code AdNaseum uses is [here](https://github.com/dhowe/AdNauseam/blob/bc24466ed09403f3acb780a0b790bb36439664ea/lib/ff/abpcomp.js) Of course, they're using the Addon SDK...

**Comment by owise1** [comment]
unbundled! #57
