### ISSUE TITLE
Migrate to Mozilla Addons SDK

### ISSUE THREAD

**Issue by slambert** [slambert/Add-Art#49]
So needed.

https://developer.mozilla.org/en-US/Add-ons/SDK

**Comment by coreytegeler** [comment]
https://github.com/slambert/Add-Art/tree/sdk

**Comment by coreytegeler** [comment]
@slambert here's the branch I'm working off of

definitely going to need some help porting the rest of the script after I get the interface designed and built (which is on its way!)

**Comment by owise1** [comment]
done in v2
