### ISSUE TITLE
add Tooltip Credits

### ISSUE THREAD

**Issue by slambert** [slambert/Add-Art#5]
Migrated from old system...

Mar 19 2008 * 21:54
Reported by: 	Mushon  

By adding a title attribute to the images we can easily add a credit to the artist. Like:

The credit can be taken directly from the image name, saving us the need to save a metadata file for the images.

**Changelog:
Modified by Mushon – Mar 19 2008 * 21:58**

The HTML it stripped was something like (ignore spaces)

< img title=”Add-Artist: Steve-Lambert” src=”chrome://addart/skin/Steve-Lambert88×31.jpg” / >

**Modified by Steve Lambert – Mar 26 2008 * 20:41**
    * Assigned user reset (from jamie)
    * Milestone set to 1.0 "talks to add-art.org"

Jamie says this needs to be part of the XML downloading thing.
Modified by Steve Lambert – May 02 2008 * 02:54

    * Component set to add-art Firefox extension

**Modified by Jamie Wilkinson – May 02 2008 * 12:42**

I commited a patch a while back that parses artbanners8-800x600.jpg into a title attribute of “artbanners” Tragically it’s not very useful until we can support dynamic file naming.

Right now we’re looking for artbanners#{RANDOMNUMBER}-#{SIZEIWANT}.jpg. Firefox can’t browse the local filesystem (or chrome) so we can’t explore it and find stuff like picasso-#{SIZEIWANT}.jpg. Thus this won’t really be doable until we have some way of knowing dynamic file names, e.g. “XML downloading thing”

Note: this doesn’t necessarily mean said XML file needs to be downloaded from a remote source—it could very well be stored in the extension and updated with each release the same way the static files are.

**Modified by Steve Lambert – Jan 17 2009 * 16:14**
    * Milestone changed from 1.0 "talks to add-art.org" to Attribution

**Modified by Matt Katz – Jan 17 2009 * 16:25**

I found out how to do a dynamic script include from an XBL style. This might let us do dynamic image names… http://groups.google.com/group/mozilla.dev.tech.xbl/browse_thread/thread/1cb938582c85925c/ce1e0517cc5d2fee?lnk=gst&q=include+script#ce1e0517cc5d2fee

**Modified by Steve Lambert – Jan 17 2009 * 16:27**

Matt Katz is researching this a bit. Hoping that we can insert a variable like so:

< img title=”$VARIABLE1” src=”chrome://addart/skin/1artbanner88×31.jpg” / >

Some code (to be written) would fulfill the variable by getting info from within the .jar file used to update the images. This is the plan right now at least.

Help appreciated.

**Comment by owise1** [comment]
you can do this now #57
