### ISSUE TITLE
Block more kinds of ads - scripts and stuff

### ISSUE THREAD

**Issue by slambert** [slambert/Add-Art#52]
Under addart/components/addartAdChanger.js look for comments like this:

`//Here possible should be done some work with script-based ads`

Would be great to block more kinds of ads.

See also: https://github.com/slambert/Add-Art/issues/8

**Comment by owise1** [comment]
here's where that happens now: https://github.com/slambert/Add-Art/blob/master/data/js/document_end.js. This could definitely be improved

**Comment by owise1** [comment]
It's now using ad block plus's list of ad selectors. this should catch a lot more
