### ISSUE TITLE
get working without addart.jar

### ISSUE THREAD

**Issue by slambert** [slambert/Add-Art#54]
According to feedback from AOM reviewer:

> 1) The add-on contains JAR file. This can result in performance issues in add-ons that target Gecko 4 and above. You should no longer use JAR files to package your chrome files. Please unpack this package to chrome directory and remove JAR file. Please see (https://developer.mozilla.org/en/Extensions/Updating_extensions_for_Firefox_4#XPI_unpacking) for more information.

> Not using JAR files should also help with addon maintenance and prevent problems such as duplication.

I quickly tried not creating the addart.jar file and running addon, but it didn't work. `<em:unpack>` is already specified in our install.rdf...

**Comment by slambert** [comment]
Got the feedback again:

> Comments:
> This version has been approved for the public.

> Please note the following for the next update:
> 1) The add-on contains JAR file. This can result in performance issues in add-ons that target Gecko 4 and above. You should no longer use JAR files to package your chrome files. Please unpack this package to chrome directory and remove JAR file. Please see (https://developer.mozilla.org/en/Extensions/Updating_extensions_for_Firefox_4#XPI_unpacking) for more information.

**Comment by owise1** [comment]
no jar in v2 #57
