### ISSUE TITLE
Check for ABP (or equivalent) install and, if missing, prompt user to install.

### ISSUE THREAD

**Issue by davidhedlund** [slambert/Add-Art#55]
Add-Art can be used with forks of Adblock Plus including Adblock, Adblock Edge, and SpyBlock (part of GNU IceCat).

Please remove the enforced installation of Adblock Plus.

Here's a list of blocking add-ons:
* Adblock Plus
* Adblock
* Adblock Edge

**Comment by mattkatz** [comment]
That's very interesting and cool! We want to make sure that folks either have one of those installed or that we install one for them. How would we be able to detect it for them? 

On March 18, 2015 6:04:54 AM EDT, davidhedlund <notifications@github.com> wrote:
>Add-Art can be used with forks of Adblock Plus including Adblock,
>Adblock Edge, and SpyBlock (part of GNU IceCat).
>
>Please remove the enforced installation of Adblock Plus. I'm happy with
>SpyBlock.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/slambert/Add-Art/issues/55

-- 
Sent from Kaiten Mail. Please excuse my brevity.

**Comment by davidhedlund** [comment]
On 2015-03-18 17:12, mattkatz wrote:
> That's very interesting and cool! We want to make sure that folks 
> either have one of those installed or that we install one for them. 
> How would we be able to detect it for them?
>
> On March 18, 2015 6:04:54 AM EDT, davidhedlund 
> <notifications@github.com> wrote:
> >Add-Art can be used with forks of Adblock Plus including Adblock,
> >Adblock Edge, and SpyBlock (part of GNU IceCat).
> >
> >Please remove the enforced installation of Adblock Plus. I'm happy with
> >SpyBlock.
> >
> >---
> >Reply to this email directly or view it on GitHub:
> >https://github.com/slambert/Add-Art/issues/55
>
> -- 
> Sent from Kaiten Mail. Please excuse my brevity.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/slambert/Add-Art/issues/55#issuecomment-83039089>.
>
I'm sure that the "This add-on requires the following add-ons to work 
properly:" box is just fine in 
https://addons.mozilla.org/en-US/firefox/addon/add-art/?src=search as 
its very visible. It does what its suppose to, get attention from the 
user to install required add-ons by choice.


I would make sure the text goes "This add-on requires one of the 
following add-ons to work properly:" and add:
* Adblock Plus
* Adblock
* Adblock Edge

to the box.


Please inform Mozilla to add such option if its not possible for you to 
do so.

**Comment by slambert** [comment]
@davidhedlund We were planning on doing this in a future release. What @mattkatz was asking is if you know how we can check the users browser to see what is installed. I know this is possible, and easier with the AMO SDK, but any code contributions would be appreciated.

Changing the title of this to reflect the issue.

I think the next release will not be bundled.

**Comment by dhowe** [comment]
So we are currently checking two options (adblock-plus and adblock-edge), but this code ([line 190](https://github.com/dhowe/AdNauseam/blob/master/lib/ff/abpcomp.js)) can prob be expanded to handle more cases (though there may be a better way to do it...)

**Comment by davidhedlund** [comment]
dhow, well, I use SpyBlock that is part of GNU IceCat. IceCat has become very popular recently as its in very active development.

**Comment by davidhedlund** [comment]
@dhowe @slambert I've switched to uBlock now, you should add that to the list as well. And uBlock Origin if possible.

**Comment by slambert** [comment]
@dhowe just went to that link you provided above and got a 404. I think the file you were using isn't in that directory anymore?

**Comment by dhowe** [comment]
https://github.com/dhowe/AdNauseam/blob/master/lib/ff/adncomp.js#L99

**Comment by owise1** [comment]
v2 has no dependencies #57
