### ISSUE TITLE
many replacement art images broken:  images.jar has non-jpg images / Add-Art can only handle jpg images

### ISSUE THREAD

**Issue by brucek** [slambert/Add-Art#56]
It looks like addartAdChanger.js:308 requires all images in images.jar to be of type .jpg.
Many images are currently gif and png, and therefore don't work properly.
Basically, need to either make all images in images.jar of type .jpg, or have some way to detect and use the proper filename/extension

**Comment by slambert** [comment]
Sorry for the delay in getting back to you.

If I remember right, Firefox didn't used to care what kind of extension an image had. So you could name, for example, a png with a .jpg extension, and it would work fine. In a quick test I just did, it still works.

Filename mix-ups are more likely to cause problems.

What show are you seeing broken images in?

**Comment by owise1** [comment]
this no longer applies in v2 #57
