### ISSUE TITLE
write up a release

### ISSUE THREAD

**Issue by slambert** [slambert/Add-Art#58]
@owise1 I don't want to mess with your version numbers for the various plugins, but if we do releases here: https://github.com/slambert/Add-Art/releases we can reference that as a changelog on http://add-art.org/update/
And you can do the same for chrome and safari.

The features can dictate the 2.X number for all, and the various releases for each platform could be 2.3.XX.

Just an idea, open to better ones.

**Comment by owise1** [comment]
https://github.com/slambert/Add-Art/releases/tag/v2.2.2
