### ISSUE TITLE
custom html page loads when version updates

### ISSUE THREAD

**Issue by slambert** [slambert/Add-Art#7]
Migrated from old system.
http://dev.eyebeam.org/projects/add-art/ticket/19

On first load, user is shown what is new with the plugin, maybe some words about it and what to expect.

**Changelog:
Modified by Jamie Wilkinson – Jan 18 2008 * 13:50**

    * Component set to add-art Firefox extension

**Modified by Michael – Mar 26 2008 * 20:42**

Here is code for this

// put this at the very top // version needs to be changed for every major version change for pop up // version = ‘0.0.7.1’; firstRun(version);

function firstRun(version){

// for resetting this script for debugging // GM_setValue(‘firstRun’, 0);

// if (version != GM_getValue(‘firstRun’))){ if (!GM_getValue(‘firstRun’) || version != GM_getValue(‘firstRun’)){ addGlobalStyle(‘div#firstRun a { color: #ccf;}’); var box = document.createElement(“div”); //box.setAttribute(“title”,”Click box to expand/collapse”); box.setAttribute(“id”,”firstRun”); box.setAttribute(“style”,”position:fixed;z-index:99;top:15px;left:15px;background-color:#FF8B19;padding:4px;text-align:left;opacity:.85;font:12pt sans-serif;color:#fff;overflow:hidden;width:400px;height:auto;margin:15px;padding-bottom:15px;padding-right:15px;padding-left:15px;-moz-border-radius-bottomleft:20px;-moz-border-radius-bottomright:20px;-moz-border-radius-topleft:20px;-moz-border-radius-topright:20px;”); box.innerHTML = ‘Welcome to the Real Costs v 0.0.7.1<p>Bug Fixes:</p> Fixes bugs associated with URLs beginning with numbersComing Soon:</p> Integration with Yahoo Maps</a>, and Google Local</a> Integration with HopStop</a> and Google Transit</a>this will only appear once</p>click here to close box’; document.getElementsByTagName(“body”)[0].appendChild(box);

var listenCloseFirstRun = document.getElementById('closeFirstRun');
    listenCloseFirstRun.addEventListener("click", closeFirstRun, true);

// un-commment this out for release!!!!!!!
    GM_setValue('firstRun', version);
}

}

function closeFirstRun(){ document.getElementById(‘firstRun’).style.display = ‘none’; }

**Modified by Michael – Mar 26 2008 * 20:44**

Put this at the very top

// version needs to be changed for every major version change for pop up //
    version = '0.0.7.1';
    firstRun(version);

This does the dirty work

{{{

function firstRun(version){

// for resetting this script for debugging // GM_setValue(‘firstRun’, 0);

// if (version != GM_getValue(‘firstRun’))){ if (!GM_getValue(‘firstRun’) || version != GM_getValue(‘firstRun’)){ addGlobalStyle(‘div#firstRun a { color: #ccf;}’); var box = document.createElement(“div”); //box.setAttribute(“title”,”Click box to expand/collapse”); box.setAttribute(“id”,”firstRun”); box.setAttribute(“style”,”position:fixed;z-index:99;top:15px;left:15px;background-color:#FF8B19;padding:4px;text-align:left;opacity:.85;font:12pt sans-serif;color:#fff;overflow:hidden;width:400px;height:auto;margin:15px;padding-bottom:15px;padding-right:15px;padding-left:15px;-moz-border-radius-bottomleft:20px;-moz-border-radius-bottomright:20px;-moz-border-radius-topleft:20px;-moz-border-radius-topright:20px;”); box.innerHTML = ‘Welcome to the Real Costs v 0.0.7.1<p>Bug Fixes:</p> Fixes bugs associated with URLs beginning with numbersComing Soon:</p> Integration with Yahoo Maps</a>, and Google Local</a> Integration with HopStop</a> and Google Transit</a>this will only appear once</p>click here to close box’; document.getElementsByTagName(“body”)[0].appendChild(box);

var listenCloseFirstRun = document.getElementById('closeFirstRun');
    listenCloseFirstRun.addEventListener("click", closeFirstRun, true);

// un-commment this out for release!!!!!!!
    GM_setValue('firstRun', version);
}

} function closeFirstRun(){ document.getElementById(‘firstRun’).style.display = ‘none’; }

)))

**Modified by Steve Lambert – May 02 2008 * 02:52**

    * Assigned user set to tobi-x

get on it Tobi! Make us proud.

**Modified by Jamie Wilkinson – May 02 2008 * 12:39**

GM_* and addGlobalStyle() are GreaseMonkey functions
Firefox preference handling:

    * http://developer.mozilla.org/en/docs/nsIPrefService

And a nice wrapper around them:

    * http://www.adamgotterer.com/2007/12/06/firefox-extension-preference-handeling/

**Modified by Steve Lambert – May 27 2008 * 18:10**

Just noticed Flashgot takes you to an update page on restart i.e.: http://flashgot.net/?ver=1.0&prev=0.9.9

We could comb their code and do this.

**Modified by Steve Lambert – Jun 01 2008 * 00:27**

    * Assigned user reset (from tobi-x)

Mattk and SteveL worked really hard on this one tonight. All our work is in /branches/versionsplash. It’s not entirely there but it’s very close. Works great on one machine and inconsistent on another. Hoping to be ready for 0.5.3 release.

**Modified by Steve Lambert – Jun 21 2008 * 15:36**

    * Priority changed from Enhancement to Normal

switching to normal since this would allow us to better communicate with our users.
Modified by Steve Lambert – Jan 17 2009 * 18:46

    * Priority changed from Normal to Enhancement

**Comment by slambert** [comment]
In: Add-Art/addart/chrome/content/addart.js
If you add:
	window.open('http://add-art.org/firstrun');
to line 95, (in the section near: "//Checking for first Run after add-on installation")

It opens a new browser window when you first install it. This isn't exactly what we want, but it's something.

**Comment by coreytegeler** [comment]
do you want it to open the page every time the plugin is updated or every time a show is updated?

**Comment by slambert** [comment]
Each time the plugin is updated. Then it could send you to a page like http://add-art.org/update where we could have some info on the new features and instructions on how to use em. There's a few Firefox addons that do this. =

**Comment by coreytegeler** [comment]
ok, that part is setup now

got it in the SDK version as well

**Comment by slambert** [comment]
Woah, look at you!

Ok, I figured this page will load whenever anyone installs or updates. So on the page we can have a video about how to get up and running with Add-Art (which I still need to make), how it works, and a little version history/list of updates in the newest version. We'll get that together and then put this in a release.  Re: SDK version, did you make it a branch and post it? Because you should!

**Comment by coreytegeler** [comment]
https://github.com/slambert/Add-Art/issues/49

**Comment by slambert** [comment]
@owise1 Here's a page we can use http://add-art.org/update/
