### ISSUE TITLE
Fix Javascript based Ad Switching

### ISSUE THREAD

**Issue by slambert** [slambert/Add-Art#8]
migrated from:
http://dev.eyebeam.org/projects/add-art/ticket/60
Apr 01 2008 * 23:01
Reported by: 	Matt Katz  

Ad swapping for JS currently works by blocking the script entirely, creating a script and swapping that script in. This means alot of hand coding per url.

I’d rather see us let the JS run, attach a timer or something to have our evaluation re-run on the substituted content and then swap THAT content.

**Comment by owise1** [comment]
not sure this applies any more. so close
